### ISSUE TITLE
Add anti-phishing mechanisms

### ISSUE THREAD

**Issue by enducker** [MyFactomWallet/MyFactomWallet#4]
- In-App User Education
- Browser Certificate
- Browser Extension

**Comment by bunfield** [comment]
Broweser Extension: currently evaluating generating hash of MFW code on server and anchoring that to the factom blockchain.  The MFW extension generate a hash of client browser code received by server and the extension will compare that to anchored hash.  If code was modified the extension will warn user of a spoof site.

When the code version is updated, a new hash will be generated and the factom blockchain will be updated.

For mobile option, exploring development of MFW app to do the site validation.

**Comment by enducker** [comment]
This issue is too general to be useful.
